### ISSUE TITLE
Feature request: simpler method for integrating with vscode extensions using symlinks

### ISSUE THREAD

**Issue by W1M0R** [hverlin/mise-vscode#128]
The `mise-vscode` extension with `configureExtensionsUseSymLinks` correctly creates symlinks for the [built-in supported extensions](https://hverlin.github.io/mise-vscode/reference/supported-extensions/), given this `settings.json` extract:

```json
{
  "mise.configureExtensionsUseSymLinks": true,
  "go.goroot": "${workspaceFolder}\\.vscode\\mise-tools\\goRoot",
  "debug.javascript.defaultRuntimeExecutable": {
    "pwa-node": "${workspaceFolder}\\.vscode\\mise-tools\\node"
  },
  "go.alternateTools": {
    "go": "${workspaceFolder}\\.vscode\\mise-tools\\go"
  },
}
```

![Image](https://github.com/user-attachments/assets/f481f43a-ba5f-45f1-a0c8-c63a82c3ce72)

## The "Problem"

I want to configure an unsupported extension to also use a mise-managed tool, e.g.:

```json
  "templ.executablePath": "${workspaceFolder}\\.vscode\\mise-tools\\templ"
```

The current workflow is to create a PR and modify [this file](https://github.com/hverlin/mise-vscode/blob/main/src/utils/supportedExtensions.ts) by adding support for the extension like this:

```typescript
{
		toolNames: ["templ", "go:github.com/a-h/templ/cmd/templ"],
		extensionId: "a-h.templ",
		generateConfiguration: async ({ tool }) => {
			return {
				"templ.executablePath": tool.install_path,
			};
		},
	},
```

That approach is very powerful and allows deep integration with other vscode extensions. However, the level of effort required and the time it would take to get an updated version of the `mise-vscode` extension available, makes this approach less attractive for simple use cases.

## A potential solution

Perhaps there could be a `mise.configureExtensionsUseSymLinksAll` setting, that when set to `true`, `mise-vscode` will create symlinks for every tool as resolved by mise for the workspace. It will not automatically modify the `settings.json` file, but it will make sure that the `.vscode/mise-tools` folder is populated with symlinks for every mise tool. This allows the user to simply just add an entry to their `settings.json` file, e.g. `"templ.executablePath":"${workspaceFolder}\\.vscode\\mise-tools\\templ"`.

So for the following `mise.toml` in my workspace:

```toml
[settings]
experimental = true
idiomatic_version_file_enable_tools = ["rust"]
windows_shim_mode = "hardlink"

[tools]
go = "1.24.4"
node = "22.6.0"
"ubi:mattn/goreman" = "0.3.16"
"ubi:tailwindlabs/tailwindcss" = "4.1.5"
"ubi:wait4x/wait4x" = "3.3.1"
"go:github.com/a-h/templ/cmd/templ" = "0.3.887"
"go:github.com/josephspurrier/goversioninfo/cmd/goversioninfo" = "1.4.1"
"go:github.com/wailsapp/wails/v2/cmd/wails" = "2.9.1"
"go:github.com/go-delve/delve/cmd/dlv" = "1.24.2"
"go:github.com/evanw/esbuild/cmd/esbuild" = "0.25.5"
watchexec = "2.3.2"
xh = "0.24.1"
coreutils = "0.1.0"
bat = "0.25.0"
svu = "3.2.3"
git-chglog = "0.15.4"
task = "3.44.0"
just = "1.40.0"
gum = "0.16.1"
```

I would expect the `.vscode/mise-tools` folder to have the following symlinks:

```
.vscode/
  mise-tools/
    goRoot/
    go.exe
    node.exe
    goreman.exe
    tailwindcss.exe
    wait4x.exe
    templ.exe
    wails.exe
    dlv.exe
    esbuild.exe
    watchexe.exe
    xh.exe
    coreutils.exe
    bat.exe
    svu.exe
    git-chglog.exe
    task.exe
    just.exe
    gum.exe
```

Since this might create too many symlinks for the user's taste, one could also consider a setting that specifically indicates which of the resolved tools should be hoisted to the `mise-tools` folder, e.g.

```json
  "mise.configureExtensionsSymLinkSelected": [
    "tailwindcss",
    "templ"
  ],
```
